### PR TITLE
add transition and about modal

### PR DESCRIPTION
**Pull request by Fraulk**
add slidIn transition for mobile menu, add about modal

i just wrote the project description in the about modal
 and did basic css for the modal, i'll do better css later, unless @chocmake gonna do stylish css

### CODE REVIEW

**Comment by chocmake** [comment]
Yeah, I initially tried a slide down animation using the same margin property but since I needed the mobile menu to be contained within the main header (rather than absolutely positioned) for the background blur effect to work for both elements it resulted in the menu displaying over the Framed logo/hamburger icon while it transitioned so I opted just for an opacity transition.

Ideally if the top header height (`--header-height` var) could be excluded during the anim using a mask or some method it'd look like it's properly sliding from underneath. Only a small detail though :)

**Comment by FransBouma** [comment]
@Fraulk Could you fix the merge conflicts please? They're pretty minor (just pick one of the two blocks specified) and it's easier for you to do it (as I have no idea if the changes conflict with what your changes are doing)

**Comment by Fraulk** [comment]
i hope i didn't break anything

and about the slide down, i think it's not looking that bad so i've kept it, but feel free to remove it

**Comment by FransBouma** [comment]
Deployed. Works ok! :D

**Comment by FransBouma** [comment]
Btw, the mobile menu doesn't contain the about modal... oversight?

**Comment by Fraulk** [comment]
yeah i forgot to mention but i didnt knew where to put it actually

**Pull request merged**
